name: "Daily Fudan"

on:
  schedule:
    - cron: "17 1,8 * * *"  # scheduled at 10:17 & 16:17 (UTC+8) everyday
  workflow_dispatch:

env:
  # auto merge from y1ndan/genshin-impact-helper, default: false
  ALLOW_MERGE: 'true'
  RUN_ENV: 'prod'
  TZ: 'Asia/Shanghai'

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master

      

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-3000 -n 1)

      - name: Run sign
        run: |
          export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 ./dailyFudan.py '${{ secrets.FUDAN }}'
